#ifndef ED_WORDS_H
#define ED_WORDS_H

#define ED_W_MENU_FILE 0u
#define ED_W_MENU_EDIT 1u
#define ED_W_MENU_SEARCH 2u
#define ED_W_MENU_VIEW 3u
#define ED_W_MENU_ENCODING 4u
#define ED_W_MENU_LANGUAGE 5u
#define ED_W_MENU_WINDOW 6u
#define ED_W_NEW 7u
#define ED_W_OPEN 8u
#define ED_W_RELOAD 9u
#define ED_W_SAVE 10u
#define ED_W_SAVE_AS 11u
#define ED_W_SAVE_ALL 12u
#define ED_W_CLOSE 13u
#define ED_W_CLOSE_ALL 14u
#define ED_W_CLOSE_OTHERS 15u
#define ED_W_EXIT 16u
#define ED_W_UNDO 17u
#define ED_W_REDO 18u
#define ED_W_CUT 19u
#define ED_W_COPY 20u
#define ED_W_PASTE 21u
#define ED_W_DELETE 22u
#define ED_W_SELECT_ALL 23u
#define ED_W_DUP_LINE 24u
#define ED_W_DEL_LINE 25u
#define ED_W_LINE_UP 26u
#define ED_W_LINE_DOWN 27u
#define ED_W_INDENT 28u
#define ED_W_UNINDENT 29u
#define ED_W_UPPER 30u
#define ED_W_LOWER 31u
#define ED_W_TRIM 32u
#define ED_W_EOL_CRLF 33u
#define ED_W_EOL_LF 34u
#define ED_W_EOL_CR 35u
#define ED_W_OVERWRITE 36u
#define ED_W_FIND 37u
#define ED_W_FIND_NEXT 38u
#define ED_W_FIND_PREV 39u
#define ED_W_REPLACE 40u
#define ED_W_GOTO 41u
#define ED_W_TOOLBAR 42u
#define ED_W_STATUS 43u
#define ED_W_NUMBERS 44u
#define ED_W_SPACES 45u
#define ED_W_WRAP 46u
#define ED_W_ZOOM_IN 47u
#define ED_W_ZOOM_OUT 48u
#define ED_W_ZOOM_RESET 49u
#define ED_W_FONT_TEXT 50u
#define ED_W_FONT_UI 51u
#define ED_W_TONGUE 52u
#define ED_W_NORMAL_TEXT 53u
#define ED_W_TAB_NEXT 54u
#define ED_W_TAB_PREV 55u
#define ED_W_L_FIND 56u
#define ED_W_L_REPLACE 57u
#define ED_W_L_GOTO 58u
#define ED_W_B_NEXT 59u
#define ED_W_B_PREV 60u
#define ED_W_B_CASE 61u
#define ED_W_B_WORD 62u
#define ED_W_B_REGEX 63u
#define ED_W_B_REPLACE 64u
#define ED_W_B_ALL 65u
#define ED_W_B_GO 66u
#define ED_W_N_NOT_FOUND 67u
#define ED_W_N_WRAPPED 68u
#define ED_W_N_REPLACED 69u
#define ED_W_N_NO_MEMORY 70u
#define ED_W_N_BAD_PATTERN 71u
#define ED_W_S_LN 72u
#define ED_W_S_COL 73u
#define ED_W_S_POS 74u
#define ED_W_S_SEL 75u
#define ED_W_S_LENGTH 76u
#define ED_W_S_LINES 77u
#define ED_W_S_INS 78u
#define ED_W_S_OVR 79u
#define ED_W_S_NORMAL 80u
#define ED_W_S_CONFLICT 81u
#define ED_W_S_SAVE_FAILED 82u
#define ED_W_S_MISSING 83u
#define ED_W_S_EOL_LF 84u
#define ED_W_S_EOL_CRLF 85u
#define ED_W_S_EOL_CR 86u
#define ED_W_P_FONT_TEXT 87u
#define ED_W_P_FONT_UI 88u
#define ED_W_P_TONGUE 89u
#define ED_W_P_DEFAULT 90u
#define ED_W_P_ENGLISH 91u
#define ED_W_P_FILTER 92u
#define ED_W_TAB_NEW 93u
#define ED_W_ASK_TITLE 94u
#define ED_W_ASK_TEXT 95u
#define ED_W_ASK_SAVE 96u
#define ED_W_ASK_DISCARD 97u
#define ED_W_ASK_CANCEL 98u
#define ED_W_ERASE 99u
#define ED_W_ERASE_ASK 100u
#define ED_W_COUNT 101u

#endif
